version: "3"
services:
  ml-pipeline:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    depends_on:
      - ml-data
  ml-data:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - ml-data:/var/lib/postgresql/data
volumes:
  ml-data: